Repository maple-labs/debt-locker, pull requests merged in 2021-11, with the labels that each got.

#19 feat: Capture Funds
  contracts/DebtLocker.sol
  contracts/DebtLockerStorage.sol
  contracts/interfaces/IDebtLocker.sol
  contracts/test/DebtLocker.t.sol
  contracts/test/accounts/PoolDelegate.sol
Labels: Priority: Medium, Status: Ready for Review

#23 feat: fixed audit findings
  contracts/DebtLocker.sol
  contracts/test/DebtLocker.t.sol
Labels: Priority: High, Status: Ready for Review

#22 chore: Make internal audit changes
  README.md
  contracts/DebtLocker.sol
  contracts/test/DebtLocker.t.sol
Labels: Priority: High, Status: Work In Progress
