Repository maple-labs/debt-locker, pull requests merged in 2021-12, with the labels that each got.

#35 fix: Test shortfall ocasionally failing
  contracts/test/DebtLocker.t.sol
Labels: Priority: High, Status: Ready for Review

#34 chore: chore: Prevent zero `mapleGlobals` in factory deployment
  contracts/DebtLockerFactory.sol
Labels: Priority: High, Status: Ready for Review

#28 feat: Add ERC-20 whitelist check in debt-locker inititalize (SC-4149)
  contracts/DebtLockerInitializer.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/DebtLocker.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review

#31 feat: Manual `stopLiquidation` function to prevent `claim` DoS (SC-4211)
  contracts/DebtLocker.sol
  contracts/interfaces/IDebtLocker.sol
  contracts/test/DebtLocker.t.sol
  contracts/test/accounts/PoolDelegate.sol
Labels: Priority: High, Status: Ready for Review

#37 feat: Cleanup and more unit testing
  contracts/DebtLocker.sol
  contracts/test/DebtLocker.t.sol
  contracts/test/accounts/PoolDelegate.sol
  contracts/test/mocks/DebtLockerHarness.sol
  contracts/test/mocks/ManipulatableDebtLocker.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review

#41 chore: Remove TODO on pullFunds (C4 #10)
  contracts/DebtLocker.sol
Labels: Priority: Medium, Status: Ready for Review

#42 chore: strict 0.8.7 (c4 #23)
  contracts/DebtLocker.sol
  contracts/DebtLockerFactory.sol
  contracts/DebtLockerInitializer.sol
  contracts/DebtLockerStorage.sol
  contracts/interfaces/IDebtLocker.sol
  contracts/interfaces/IDebtLockerFactory.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/DebtLocker.t.sol
  contracts/test/mocks/DebtLockerHarness.sol
  contracts/test/mocks/ManipulatableDebtLocker.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#43 fix: Add named returns where missing (c4 #25)
  contracts/DebtLocker.sol
Labels: Priority: Medium, Status: Ready for Review

#44 fix: `handleClaimOfRepossessed` gas optimization (C4 #66)
  contracts/DebtLocker.sol
Labels: Priority: Medium, Status: Ready for Review

#45 fix: `getExpectedAmount` gas savings (C4 #62)
  contracts/DebtLocker.sol
Labels: Priority: Medium, Status: Ready for Review

#46 fix: Use `!= 0` instead of `> 0` (c4 #24)
  contracts/DebtLocker.sol
Labels: Priority: Medium, Status: Ready for Review

#47 fix: Input validation for `setAllowedSlippage` (c4 #45)
  contracts/DebtLocker.sol
  contracts/test/DebtLocker.t.sol
Labels: Priority: Medium, Status: Ready for Review

#50 chore: Remove unused getters
  contracts/DebtLocker.sol
  contracts/interfaces/IDebtLocker.sol
Labels: Priority: Medium, Status: Ready for Review

#51 feat: Add liquidator address to pullFunds parameters (SC-4344)
  contracts/DebtLocker.sol
  contracts/interfaces/IDebtLocker.sol
  contracts/test/DebtLocker.t.sol
  contracts/test/accounts/PoolDelegate.sol
Labels: Status: Ready for Review

#52 formatting: Imports and natspec
  contracts/DebtLocker.sol
  contracts/interfaces/IDebtLocker.sol
Labels: Priority: High, Status: Ready for Review
